apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: clusterodm
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: clusterodm
status:
  loadBalancer: {}
