apiVersion: v1
kind: PersistentVolume
metadata:
  name: jhubdbvolume
  namespace: jhub
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  cinder: 
    fsType: ext4 
    volumeID: 399fc293-b259-4af6-a67a-80bafb0c9a07
