apiVersion: v1
kind: Pod
#This pod runs dbdata container in priviledged mode to allow volume resize
metadata:
  creationTimestamp: null
  labels:
    run: dbdata-resize
  name: dbdata-resize
spec:
  restartPolicy: Never

  #Volume to resize
  volumes:
  - name: dbdata
    persistentVolumeClaim:
      claimName: dbdata

  containers:
  #WebODM app
  - name: dbdata-container
    securityContext: { privileged: true } #To allow resize2fs
    command: ["/bin/bash", "-c"]
    args:
      - DEVICE=$(df "/var/lib/postgresql/data" | tail -1 | awk '{ print $1 }');
        resize2fs ${DEVICE};
    image: opendronemap/webodm_db
    imagePullPolicy: ""
    name: dbdata
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: dbdata
      subPath: postgres

