---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume-0
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cinder.csi.openstack.org
    fsType: ext4
    volumeHandle: 68f26d2c-5c1e-443c-99e9-8ef879cd6017
  storageClassName: csi-sc-cinderplugin

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-sc-cinderplugin
  volumeMode: Filesystem
  volumeName: test-volume-0
---
apiVersion: v1
kind: Pod
metadata:
  name: test-0
  namespace: default
spec:
  containers:
  - name: test
    #image: ubuntu:22.04
    image: bitnami/git:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: test-data
      mountPath: /mnt/data
    #Also mounts the S3 volume for backing up
    - name: asdc-store
      mountPath: /mnt/store
  restartPolicy: Always
  volumes:
  - name: test-data
    persistentVolumeClaim:
      claimName: test-pvc-0
  - name: asdc-store
    persistentVolumeClaim:
      claimName: asdc-store-pvc

