apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker
  name: broker
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: broker
status:
  loadBalancer: {}
