apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  strategy: {}
  template:
    metadata:
      labels:
        app: broker
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: redis
        imagePullPolicy: ""
        name: broker
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
