---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  capacity:
    storage: ${DB_VOLUME_SIZE}Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cinder.csi.openstack.org
    fsType: ext4
    volumeHandle: ${DB_VOLUME_ID}
  storageClassName: csi-sc-cinderplugin

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${DB_VOLUME_SIZE}Gi
  storageClassName: csi-sc-cinderplugin
  volumeMode: Filesystem
  volumeName: db-volume


