apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbvolume
spec:
  capacity:
    storage: ${DB_VOLUME_SIZE}Gi
  accessModes:
    - ReadWriteOnce
  cinder: 
    fsType: ext4 
    volumeID: ${DB_VOLUME_ID} 
  claimRef:
    name: dbdata
    namespace: default
