#Pass env settings to fluxcd
#via ConfigMaps and Secret
#See: https://github.com/flux/zero-to-flux-k8s/blob/main/flux/values.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-configmap
  namespace: flux-system
data:
  #Misc
  cluster_env: "dev"
  CLUSTER: ${CLUSTER}
  ZONE: ${ZONE}

  #webodm
  WEBAPP_IP: "${WEBAPP_IP}"
  WEBAPP_VOLUME_SIZE: "${WEBAPP_VOLUME_SIZE}"
  WEB_VOLUME_ID: "${WEB_VOLUME_ID}"
  WEBAPP_HOST: "${WEBAPP_HOST}"
  DB_VOLUME_SIZE: "${DB_VOLUME_SIZE}"
  DB_VOLUME_ID: "${DB_VOLUME_ID}"
  DB_VOLUME_SIZE: "${DB_VOLUME_SIZE}"

  #tusd
  TUSD_VOLUME_SIZE: "${TUSD_VOLUME_SIZE}"

  #gpu-operator
  #Must match version in current build at https://github.com/AuScalableDroneCloud/nvidia-driver-build-fedora
  NVIDIA_DRIVER: "460.32.03"
  #NVIDIA_DRIVER: "470.57.02" #Errors due to gcc version? Might need a newer coreos
  #NVIDIA_DRIVER: "510.47.03"

  #jupyterhub
  JHUB_HOST: ${JHUB_HOST}
  JHUB_LOADBALANCER_IP: ${JHUB_LOADBALANCER_IP}

---
apiVersion: v1
kind: Secret
metadata:
  name: flux-secrets
  namespace: flux-system
type: Opaque
stringData:
  #botkube
  BOTKUBE_SLACK_TOKEN: "${BOTKUBE_SLACK_TOKEN}"

  #webodm
  WO_AUTH0_DOMAIN: "${WO_AUTH0_DOMAIN}"
  WO_AUTH0_SUBDOMAIN: "${WO_AUTH0_SUBDOMAIN}"
  WO_AUTH0_KEY: "${WO_AUTH0_KEY}"
  WO_AUTH0_SECRET: "${WO_AUTH0_SECRET}"
  WO_ENCRYPTION_KEY: "${WO_ENCRYPTION_KEY}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  #s3 object store on OpenStack
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  #s3 for cesium (APPF)
  CESIUM_AWS_ACCESS_KEY_ID: $CESIUM_AWS_ACCESS_KEY_ID
  CESIUM_AWS_SECRET_ACCESS_KEY: $CESIUM_AWS_SECRET_ACCESS_KEY

  #jupyterhub
  JHUB_ADMIN_USER: ${JHUB_ADMIN_USER}
  JHUB_CRYPT_KEEPER_KEY1: ${JHUB_CRYPT_KEEPER_KEY1}
  JHUB_SECRET_TOKEN: ${JHUB_SECRET_TOKEN}

---
#Init scripts for WebODM, NodeODM
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-configmap
  namespace: default
data:
  node_setup.sh: |
${NODEODM_SETUP_SCRIPT_CONTENT}
  asdc_init.sh: |
${WEBODM_SETUP_SCRIPT_CONTENT}



