apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-configmap
  namespace: jupyterhub
data:
  values.yaml: |
    proxy:
      https:
        enabled: true
        hosts:
          - ${JHUB_HOST}
        letsencrypt:
          contactEmail: ${JHUB_ADMIN_USER}
      service:
        loadBalancerIP: ${JHUB_LOADBALANCER_IP}
    hub:
      config:
        Auth0OAuthenticator:
          oauth_callback_url: https://${JHUB_HOST}/hub/oauth_callback
          scope:
            - openid
            - email
        Authenticator:
          admin_users:
            - ${JHUB_ADMIN_USER}
          enable_auth_state: true #Test
          auto_login: true
        JupyterHub:
          authenticator_class: auth0
