#See: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-configmap
  namespace: jupyterhub
data:
  values.yaml: |
    proxy:
      https:
        enabled: true
        hosts:
          - ${JHUB_HOST}
        letsencrypt:
          contactEmail: ${JHUB_ADMIN_USER}
      service:
        loadBalancerIP: ${JHUB_LOADBALANCER_IP}
    hub:
      config:
        Auth0OAuthenticator:
          oauth_callback_url: https://${JHUB_HOST}/hub/oauth_callback
          scope:
            - openid
            - email
        Authenticator:
          admin_users:
            - ${JHUB_ADMIN_USER}
          auto_login: true
        JupyterHub:
          authenticator_class: auth0
      #Allow running on compute nodes
      tolerations:
      - key: "compute"
        operator: "Exists"
        effect: "NoSchedule"
    #Require taint on node to schedule pod (default is prefer)
    #https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html
    scheduling:
      userPods:
        nodeAffinity:
          # matchNodePurpose valid options:
          # - ignore
          # - prefer (the default)
          # - require
          #matchNodePurpose: require
          matchNodePurpose: prefer
    singleuser:
      extraEnv:
        JUPYTERHUB_URL: "https://${JHUB_HOST}"

