apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ${NODE_NAME}
spec:
  ports:
  - port: ${NODE_PORT}
    targetPort: ${NODE_PORT}
  selector:
    app: ${NODE_NAME}
status:
  loadBalancer: {}
