#Deployment of NodeODM / NodeMICMAC or other procesing nodes
#NOTE: can't use replicas for deployment cluster size
# as cinder volumes can not be shared and unique id must be specified
apiVersion: v1
kind: Pod
metadata:
  name: ${NODE_NAME}
  labels:
    app: ${NODE_NAME}
spec:
  containers:
    - name: nodeodm
      image: ${NODE_IMAGE}
      volumeMounts:
        - name: odm-volume
          mountPath: "/var/www/data"
  volumes:
    - name: odm-volume
      cinder:
        volumeID: ${NODE_VOLUME_ID}
        fsType: ext4

