---
#ConfigMap for script to register the node on ClusterODM
#(also fixes the ./tmp location issue)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeodm-config-map
data:
  setup.sh: |
${NODE_SETUP_SCRIPT_CONTENT}


