#Deployment of NodeODM / NodeMICMAC or other procesing nodes
#NOTE: can't use replicas for deployment cluster size
# as cinder volumes can not be shared and unique id must be specified
apiVersion: v1
kind: Pod
metadata:
  name: ${NODE_NAME}
  labels:
    app: ${NODE_NAME}
    type: ${NODE_TYPE}
spec:
  containers:
    - name: nodeodm
      image: ${NODE_IMAGE}
      args: ${NODE_ARGS}
      volumeMounts:
        - name: ${NODE_VOLUME_NAME}
          mountPath: "/var/www/data"
      # https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/
      #resources:
      #  limits:
      #    nvidia.com/gpu: 1 # requesting 1 GPU
  volumes:
    - name: ${NODE_VOLUME_NAME}
      cinder:
        volumeID: ${NODE_VOLUME_ID}
        fsType: ext4

  #Use anti-affinity to prevent similar instances running on same k8s node
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "type"
                operator: In
                values:
                - ${NODE_TYPE}
          topologyKey: "kubernetes.io/hostname"

  # Zombie repellent
  # https://www.back2code.me/2020/02/zombie-processes-back-in-k8s/
  # https://stackoverflow.com/questions/50803268/kubernetes-equivalent-of-docker-run-init
  shareProcessNamespace: true

