#This DaemonSet mounts the extra disk /dev/vdb on the nodes
#Uses gpu label to detect new nodes
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scratch-volume-mounter
  namespace: default
spec:
  selector:
    matchLabels:
      app: scratch-volume-mounter
  template:
    metadata:
      labels:
        app: scratch-volume-mounter
    spec:
      hostPID: true
      hostIPC: true

      #Run on new hardware nodes only
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - A100-PCIE-40GB
                - A40

      #Allow running on compute nodes
      tolerations:
      - key: "compute"
        operator: "Exists"
        effect: "NoSchedule"

      initContainers:
      - name: local-disk-init
        image: docker.io/alpine:3.13
        command:
          - nsenter
        args:
          - '--target=1'
          - '-m'
          - '--'
          - 'sh'
          - '-c'
          - 'mkdir -p /mnt/scratch; mount /dev/vdb /mnt/scratch; chcon -Rt svirt_sandbox_file_t /mnt/scratch; chmod a+xrw /mnt/scratch'
        #chcon fixes selinux access denied issue in pods: https://github.com/projectatomic/adb-atomic-developer-bundle/issues/117
        securityContext:
          privileged: true

      #The actual work must only run once (above), but if daemonset pod exits
      #will always restart, so we need this hack...
      containers:
        - name: dummy 
          image: kubernetes/pause

