apiVersion: v1
kind: Secret
metadata:
  name: shared-data-cephfs-secret
  namespace: jupyterhub
data:
  key: ${ASDC_SHARED_DATA_CEPHFS_KEY_BASE64}  # the base64-encoded string of the already-base64-encoded key `ceph auth get-key` outputs
