#https://github.com/tus/tusd/blob/master/docs/installation.md
#https://github.com/sagikazarmark/helm-charts/tree/master/charts/tusd
image:
  # -- Name of the image repository to pull the container image from.
  repository: tusproject/tusd

  # -- [Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) for updating already existing images on a node.
  pullPolicy: IfNotPresent

  # -- Image tag override for the default value (chart appVersion).
  #tag: "latest"
  tag: "v2.0.0-rc4"

# -- Additional storage [volumes](https://kubernetes.io/docs/concepts/storage/volumes/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
volumes:
  - name: tusd-csi-cinder
    persistentVolumeClaim:
      claimName: tusd-cinder-pvc
      readOnly: false
#      fsType: ext4 # default is ext4

# -- Additional [volume mounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
volumeMounts:
  - name: tusd-csi-cinder
    mountPath: /srv/tusd-data/data

# -- Pod [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context) for details.
podSecurityContext:
  fsGroup: 1000 #Mount the filesystem as correct user

# -- List of container arguments.
# **Note:** This is a temporary solution until there is a better way to configure the application.
# See [sagikazarmark/helm-charts#49](https://github.com/sagikazarmark/helm-charts/issues/49) for details.
#containerArgs: []
containerArgs:
  - '-verbose'
  - '-behind-proxy'

#env:
#  AWS_REGION: "us-east-1" #Needs to have this value, even for service with no region defined

service:
  # -- Kubernetes [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
  #type: ClusterIP
  type: LoadBalancer

  # -- (string) Only applies when the service type is LoadBalancer. Load balancer will get created with the IP specified in this field.
  loadBalancerIP: ${TUSD_IP}

ingress:
  # -- Enable [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/).
  enabled: true

  # -- Ingress host configuration.
  # @default -- See [values.yaml](values.yaml).
  hosts:
    - host: ${TUSD_HOST}
      paths:
        - path: /
          pathType: ImplementationSpecific


