apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp-service
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: "https"
    port: 443
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: ${WEBAPP_IP}
  selector:
    app: webapp

