apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webapp-claim0
  name: webapp-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${WEBAPP_VOLUME_SIZE}Gi
status: {}
