---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-volume
spec:
  capacity:
    storage: ${WEBAPP_VOLUME_SIZE}Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cinder.csi.openstack.org
    fsType: ext4
    volumeHandle: ${WEB_VOLUME_ID}
  storageClassName: csi-sc-cinderplugin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${WEBAPP_VOLUME_SIZE}Gi
  storageClassName: csi-sc-cinderplugin
  volumeMode: Filesystem
  volumeName: webapp-volume



