apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-volume
spec:
  capacity:
    storage: ${WEBAPP_VOLUME_SIZE}Gi
  accessModes:
    - ReadWriteOnce
  cinder: 
    fsType: ext4 
    volumeID: ${WEB_VOLUME_ID} 
  claimRef:
    name: webapp-claim0
    namespace: default
